name: main_workflow.yml
on: push
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Build
      run: |
        xcodebuild \
        CODE_SIGNING_ALLOWED=NO
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Lint
      run: swiftlint --config .swiftlint.yml
