name: main_workflow.yml
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Build
      run: |
        xcodebuild \
        CODE_SIGNING_ALLOWED=NO
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Run SwiftLint -> SARIF
      run: swiftlint --config .swiftlint.yml --reporter sarif --output swiftlint.sarif
    - name: Upload SARIF to GitHub Code Scanning
    uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: swiftlint.sarif
