name: main_workflow.yml
on: push
jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Build
      run: xcodebuild
